name: easy_carbs
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.9
  flutter_riverpod: ^3.1.0
  uuid: ^3.0.0
  drift_db_viewer: ^2.1.0
  flutter_picker_plus: ^1.5.4
  image_picker: ^1.2.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  dartdoc: ^8.2.2
    
  flutter_lints: ^5.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.7.1

flutter:
  uses-material-design: true

  
  assets:
    - assets/defaults/default-burger.jpg
    - assets/defaults/ec-default.jpg
    - assets/splash/splashlogo.png
    - assets/icon/ec-icon.png


flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/splash/splashlogo.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#000000"
    image: assets/splash/splashlogo.png


flutter_launcher_icons:
  android: true
  ios: false

  image_path: "assets/icon/ec-icon.png"

  adaptive_icon_background: "#111827"
  adaptive_icon_foreground: "assets/icon/ec-icon.png"